name: oppychat_dev_project

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend
    tty: true  # 👈 Mantiene el contenedor abierto para debug
    stdin_open: true
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_credentials.json
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./profiles:/app/profiles
    depends_on:
      chat-postgres:
        condition: service_healthy # 👈 Espera a que Postgres esté LISTO
      chat-redis:
        condition: service_started
    networks:
      - chat-net
    # Modificamos el comando para que no explote si no hay migraciones pendientes
    command: >
      sh -c "alembic upgrade head || echo 'Migraciones fallidas o no encontradas, iniciando app de todas formas...' &&
             uvicorn src.main:app --host=0.0.0.0 --port=8000 --proxy-headers --reload --log-level debug"

  chat-postgres:
    image: postgres:15-alpine
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-jcampillay}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-BTC.100K.jc}
      POSTGRES_DB: ${DB_NAME:-OppyChat}
    ports:
      - "5442:5432"
    healthcheck: # 👈 Vital para que el backend no intente conectar antes de tiempo
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - chat-net

  chat-redis:
    image: redis:alpine
    container_name: chat-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chat-net
    command: redis-server --requirepass ${REDIS_PASSWORD:-oppy_secret_pass}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-oppy_secret_pass}

  chat-pgadmin:
    image: dpage/pgadmin4
    container_name: chat-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7070:80"
    networks:
      - chat-net
    depends_on:
      - chat-postgres

networks:
  chat-net:

volumes:
  postgres_data:
  pgadmin_data: