"""add_auth_module_tables

Revision ID: 0001
Revises: 
Create Date: 2026-03-19 15:26:40.522127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('system_prompt', sa.String(length=2000), nullable=False),
    sa.Column('is_tts_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('selected_voice', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('native_language', sa.String(length=50), server_default='Spanish', nullable=False),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('user_image', sa.String(length=1048), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('has_accepted_terms', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('username'),
    schema='chat'
    )
    op.create_index('idx_user_email_username', 'users', ['email', 'username'], unique=False, schema='chat')
    op.create_table('email_confirmation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=1048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='chat'
    )
    op.create_index('idx_email_confirmation_token_token', 'email_confirmation_tokens', ['token'], unique=False, schema='chat')
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', schema='chat', inherit_schema=True), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    schema='chat'
    )
    op.create_index('idx_message_chat_id', 'messages', ['chat_id'], unique=False, schema='chat')
    op.create_index('idx_message_user_id', 'messages', ['user_id'], unique=False, schema='chat')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='chat'
    )
    op.create_index('idx_reset_token_expires_at', 'password_reset_tokens', ['expires_at'], unique=False, schema='chat')
    op.create_index('idx_reset_token_token', 'password_reset_tokens', ['token'], unique=False, schema='chat')
    op.create_index('idx_reset_token_user_id', 'password_reset_tokens', ['user_id'], unique=False, schema='chat')
    op.create_table('read_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='chat'
    )
    op.create_index('idx_refresh_token_expires_at', 'refresh_tokens', ['expires_at'], unique=False, schema='chat')
    op.create_index('idx_refresh_token_token', 'refresh_tokens', ['token'], unique=False, schema='chat')
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False, schema='chat')
    op.create_table('user_chat',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id'),
    schema='chat'
    )
    op.create_table('user_session_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_index('idx_session_login_time', 'user_session_history', ['login_time'], unique=False, schema='chat')
    op.create_index('idx_session_user_id', 'user_session_history', ['user_id'], unique=False, schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fct_device_usage',
    sa.Column('usage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usage_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usage_date', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('dim_service',
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('dim_device',
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index('idx_session_user_id', table_name='user_session_history', schema='chat')
    op.drop_index('idx_session_login_time', table_name='user_session_history', schema='chat')
    op.drop_table('user_session_history', schema='chat')
    op.drop_table('user_chat', schema='chat')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens', schema='chat')
    op.drop_index('idx_refresh_token_token', table_name='refresh_tokens', schema='chat')
    op.drop_index('idx_refresh_token_expires_at', table_name='refresh_tokens', schema='chat')
    op.drop_table('refresh_tokens', schema='chat')
    op.drop_table('read_status', schema='chat')
    op.drop_index('idx_reset_token_user_id', table_name='password_reset_tokens', schema='chat')
    op.drop_index('idx_reset_token_token', table_name='password_reset_tokens', schema='chat')
    op.drop_index('idx_reset_token_expires_at', table_name='password_reset_tokens', schema='chat')
    op.drop_table('password_reset_tokens', schema='chat')
    op.drop_index('idx_message_user_id', table_name='messages', schema='chat')
    op.drop_index('idx_message_chat_id', table_name='messages', schema='chat')
    op.drop_table('messages', schema='chat')
    op.drop_index('idx_email_confirmation_token_token', table_name='email_confirmation_tokens', schema='chat')
    op.drop_table('email_confirmation_tokens', schema='chat')
    op.drop_index('idx_user_email_username', table_name='users', schema='chat')
    op.drop_table('users', schema='chat')
    op.drop_table('chats', schema='chat')
    # ### end Alembic commands ###
