"""add target_language and update relationships

Revision ID: 0003
Revises: 0002
Create Date: 2026-03-23 15:30:18.649261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placement_tests', sa.Column('target_language', sa.String(length=10), nullable=False), schema='chat')
    op.drop_constraint(op.f('placement_tests_user_id_key'), 'placement_tests', schema='chat', type_='unique')
    op.create_unique_constraint('_user_language_uc', 'placement_tests', ['user_id', 'target_language'], schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_language_uc', 'placement_tests', schema='chat', type_='unique')
    op.create_unique_constraint(op.f('placement_tests_user_id_key'), 'placement_tests', ['user_id'], schema='chat', postgresql_nulls_not_distinct=False)
    op.drop_column('placement_tests', 'target_language', schema='chat')
    # ### end Alembic commands ###
