"""add PlacementTest_Details

Revision ID: 0005
Revises: 0004
Create Date: 2026-03-27 11:23:58.606307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Creamos la nueva tabla
    op.create_table('placement_test_details',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('placement_test_id', sa.Integer(), nullable=False),
        sa.Column('section', sa.String(length=20), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('user_response', sa.Text(), nullable=True),
        sa.Column('feedback_text', sa.Text(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['placement_test_id'], ['chat.placement_tests.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('placement_test_id', 'section', name='_test_section_uc'),
        schema='chat'
    )

    # 2. 🚨 EL ORDEN IMPORTA AQUÍ:
    # Primero borramos la tabla que tiene la Foreign Key (user_writing_assignments)
    op.drop_table('user_writing_assignments', schema='chat')
    
    # Luego borramos la tabla de la que dependía (writing_topics)
    op.drop_table('writing_topics', schema='chat')
    
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_writing_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['chat.writing_topics.id'], name=op.f('user_writing_assignments_topic_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], name=op.f('user_writing_assignments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_writing_assignments_pkey')),
    sa.UniqueConstraint('user_id', 'target_language', name=op.f('_user_lang_assignment_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='chat'
    )
    op.create_table('writing_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('writing_topics_pkey')),
    schema='chat'
    )
    op.drop_table('placement_test_details', schema='chat')
    # ### end Alembic commands ###
