"""add chat learning-analysis and avatars tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-04-05 12:47:24.454971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='chat'
    )
    op.create_table('oppy_host_avatar_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_avatar', sa.String(length=500), nullable=False),
    sa.Column('role_usuario', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=500), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('character_traits', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_table('avatar_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('host_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_avatar', sa.String(length=500), nullable=True),
    sa.Column('role_usuario', sa.String(length=255), nullable=True),
    sa.Column('objective', sa.String(length=500), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('character_traits', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('output_format_preference', sa.String(length=50), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('selected_voice', sa.String(length=50), nullable=True),
    sa.Column('is_tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_profile_id'], ['chat.oppy_host_avatar_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    schema='chat'
    )
    op.create_table('learning_focus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('insight_summary', sa.Text(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['chat.analysis_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_table('chat_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_definition_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(length=255), nullable=False),
    sa.Column('fact_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_definition_id'], ['chat.avatar_definitions.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chats.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat.messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_table('focus_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learning_focus_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('original_segment', sa.Text(), nullable=False),
    sa.Column('corrected_segment', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('exercise_text_es', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['learning_focus_id'], ['chat.learning_focus.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat.messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_table('user_message_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('highlighted_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat.messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chat.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.add_column('chats', sa.Column('avatar_definition_id', sa.Integer(), nullable=True), schema='chat')
    op.create_foreign_key(None, 'chats', 'avatar_definitions', ['avatar_definition_id'], ['id'], source_schema='chat', referent_schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', schema='chat', type_='foreignkey')
    op.drop_column('chats', 'avatar_definition_id', schema='chat')
    op.drop_table('user_message_corrections', schema='chat')
    op.drop_table('focus_instances', schema='chat')
    op.drop_table('chat_facts', schema='chat')
    op.drop_table('learning_focus', schema='chat')
    op.drop_table('avatar_definitions', schema='chat')
    op.drop_table('oppy_host_avatar_profile', schema='chat')
    op.drop_table('analysis_categories', schema='chat')
    # ### end Alembic commands ###
