"""add AvatarDefinitionTranslation

Revision ID: 0008
Revises: 0007
Create Date: 2026-04-05 17:02:38.763462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_definition_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avatar_definition_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_avatar', sa.String(length=500), nullable=False),
    sa.Column('role_usuario', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=500), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('character_traits', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_definition_id'], ['chat.avatar_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_avatar_definition_translations_avatar_definition_id'), 'avatar_definition_translations', ['avatar_definition_id'], unique=False, schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_avatar_definition_translations_avatar_definition_id'), table_name='avatar_definition_translations', schema='chat')
    op.drop_table('avatar_definition_translations', schema='chat')
    # ### end Alembic commands ###
