"""add likes_count & scenario_category to AvatarDefinition

Revision ID: 0014
Revises: 0013
Create Date: 2026-04-07 16:59:01.993925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Agregamos las columnas permitiendo nulos inicialmente
    op.add_column('avatar_definitions', sa.Column('likes_count', sa.Integer(), nullable=True), schema='chat')
    op.add_column('avatar_definitions', sa.Column('scenario_category', sa.String(length=50), nullable=True), schema='chat')

    # 2. Seteamos likes_count a 0 para todos los registros actuales
    op.execute("UPDATE chat.avatar_definitions SET likes_count = 0")

    # 3. Ahora que no hay nulos, cambiamos la columna a NOT NULL
    op.alter_column('avatar_definitions', 'likes_count',
               existing_type=sa.Integer(),
               nullable=False,
               schema='chat')##


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatar_definitions', 'scenario_category', schema='chat')
    op.drop_column('avatar_definitions', 'likes_count', schema='chat')
    # ### end Alembic commands ###
