"""Add context_sentence

Revision ID: 0021
Revises: 0020
Create Date: 2026-07-30 17:12:03.269489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary_words', sa.Column('context_sentence', sa.Text(), nullable=True), schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary_words', 'context_sentence', schema='chat')
    # ### end Alembic commands ###
